-- MySQL Script generated by MySQL Workbench
-- 05/08/16 05:11:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cm_web_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `info_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_role` ;

CREATE TABLE IF NOT EXISTS `info_role` (
  `role_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(20) NULL COMMENT '',
  `permission` INT NOT NULL COMMENT '',
  `default` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '',
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_department` ;

CREATE TABLE IF NOT EXISTS `info_department` (
  `dept_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `dept_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`dept_id`)  COMMENT '',
  UNIQUE INDEX `dept_id_UNIQUE` (`dept_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_employee` ;

CREATE TABLE IF NOT EXISTS `info_employee` (
  `employee_id` INT NOT NULL COMMENT '',
  `employee_name` VARCHAR(45) NULL COMMENT '',
  `role_id` INT NULL COMMENT '',
  `dept_id` INT NULL COMMENT '',
  `password_hash` VARCHAR(128) NULL COMMENT '',
  `member_since` DATE NULL COMMENT '',
  PRIMARY KEY (`employee_id`)  COMMENT '',
  INDEX `dept_id_idx` (`dept_id` ASC)  COMMENT '',
  INDEX `role_id_idx` (`role_id` ASC)  COMMENT '',
  CONSTRAINT `dept_id`
    FOREIGN KEY (`dept_id`)
    REFERENCES `info_department` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `info_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thing_cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thing_cost` ;

CREATE TABLE IF NOT EXISTS `thing_cost` (
  `cost_id` INT NOT NULL COMMENT '',
  `event_time` DATETIME NULL COMMENT '',
  `record_time` DATETIME NULL COMMENT '',
  `dept_id` INT NULL COMMENT '',
  `party_employee_id` INT NULL COMMENT '',
  `cost_money` DECIMAL(10,2) NULL COMMENT '',
  `cost_label` VARCHAR(20) NULL COMMENT '',
  `cost_deail` TEXT NULL COMMENT '',
  PRIMARY KEY (`cost_id`)  COMMENT '',
  INDEX `dept_id_idx` (`dept_id` ASC)  COMMENT '',
  INDEX `party_employee_id_idx` (`party_employee_id` ASC)  COMMENT '',
  CONSTRAINT `cost_dept_id`
    FOREIGN KEY (`dept_id`)
    REFERENCES `info_department` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `party_employee_id`
    FOREIGN KEY (`party_employee_id`)
    REFERENCES `info_employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_department` ;

CREATE TABLE IF NOT EXISTS `info_department` (
  `dept_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `dept_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`dept_id`)  COMMENT '',
  UNIQUE INDEX `dept_name` (`dept_name` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `info_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_role` ;

CREATE TABLE IF NOT EXISTS `info_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  `permission` INT(11) NULL DEFAULT NULL COMMENT '',
  `default` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '',
  UNIQUE INDEX `role_name` (`role_name` ASC)  COMMENT '',
  INDEX `ix_info_role_default` (`default` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `info_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_employee` ;

CREATE TABLE IF NOT EXISTS `info_employee` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `employee_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  `member_since` DATETIME NULL DEFAULT NULL COMMENT '',
  `password_hash` VARCHAR(128) NULL DEFAULT NULL COMMENT '',
  `role_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `dept_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`employee_id`)  COMMENT '',
  INDEX `role_id` (`role_id` ASC)  COMMENT '',
  INDEX `dept_id` (`dept_id` ASC)  COMMENT '',
  CONSTRAINT `info_employee_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `info_role` (`role_id`),
  CONSTRAINT `info_employee_ibfk_2`
    FOREIGN KEY (`dept_id`)
    REFERENCES `info_department` (`dept_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `thing_cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thing_cost` ;

CREATE TABLE IF NOT EXISTS `thing_cost` (
  `cost_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `event_time` DATETIME NULL DEFAULT NULL COMMENT '',
  `record_time` DATETIME NULL DEFAULT NULL COMMENT '',
  `cost_label` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  `cost_detail` TEXT NULL DEFAULT NULL COMMENT '',
  `cost_money` FLOAT NULL DEFAULT NULL COMMENT '',
  `dept_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `party_employee_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cost_id`)  COMMENT '',
  INDEX `dept_id` (`dept_id` ASC)  COMMENT '',
  INDEX `party_employee_id` (`party_employee_id` ASC)  COMMENT '',
  CONSTRAINT `thing_cost_ibfk_1`
    FOREIGN KEY (`dept_id`)
    REFERENCES `info_department` (`dept_id`),
  CONSTRAINT `thing_cost_ibfk_2`
    FOREIGN KEY (`party_employee_id`)
    REFERENCES `info_employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
